### PR TITLE
added openSources version 1.2.0 data

### PR DESCRIPTION
**Pull request by BigMcLargeHuge**

### CODE REVIEW

**Comment by tomlutzenberger** [comment]
LGTM so far. Is this the current reviewed data?

**Comment by thinkcontext** [comment]
I noticed this appears to undo commit https://github.com/bs-detector/bs-detector/commit/047e60140317a01377e1562bde536c7cfea143ff by @selfagency which removed fusion.net and redstate.com .  Perhaps there's some discussion / clarification needed?

**Comment by BigMcLargeHuge** [comment]
@thinkcontext My apologies, fusion should have certainly been removed and I believe we agreed to remove Red State as well.  Will update

**Comment by BigMcLargeHuge** [comment]
Fixed.  @tomlutzenberger this is indeed the most up-to-date block of data, with over 200 new sources evaluated.

**Comment by tomlutzenberger** [comment]
Great! If @Bastlynn and @thinkcontext are okay with this, I will merge it in 😀

**Comment by Bastlynn** [comment]
Looks good so far

**Comment by thinkcontext** [comment]
Fine w/ me.

**Pull request merged**
