### PR TITLE
added OpenSources badges to readme, index and content

### PR DESCRIPTION
**Pull request by BigMcLargeHuge**
Thought it would be good if OpenSources had a badge for the README.

### CODE REVIEW

**Comment by tomlutzenberger** [comment]
Sounds like a good idea to me. Final decision is made by @selfagency.
How about the other way around? Do you see a way to add something discreet for BS Detector on Opensources? Would be nice to have bilateral backing 😃

**Comment by BigMcLargeHuge** [comment]
Hi Tom, I updated the code a little bit because github's markdown seemed to be having some trouble with the embedded base-64 logo.  As to your point about bilateral backing, I think that's a great idea.  Has anyone created a bs-detector badge or something like that?

**Comment by tomlutzenberger** [comment]
We still need to decide whether we keep the "smiling poop" as logo or make a new one. I made a draft last year but it seems the idea got lost.
I'll make a new issue on this.

**Comment by BigMcLargeHuge** [comment]
Did I need to do anything for these changes to be merged?

**Comment by tomlutzenberger** [comment]
Unfortunately, I couldn't reach @selfagency in a while.
I'll look at it and let you know within 12hrs.

**Comment by BigMcLargeHuge** [comment]
Cool.  I also upgraded the data file we're up to over 700 sources now.

**Comment by BigMcLargeHuge** [comment]
Thanks dude

**Pull request merged**
